/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AAdditionexpressionHashexpression extends PHashexpression
{
    private PAdditionexpression _additionexpression_;

    public AAdditionexpressionHashexpression()
    {
    }

    public AAdditionexpressionHashexpression(
        PAdditionexpression _additionexpression_)
    {
        setAdditionexpression(_additionexpression_);

    }
    public Object clone()
    {
        return new AAdditionexpressionHashexpression(
            (PAdditionexpression) cloneNode(_additionexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdditionexpressionHashexpression(this);
    }

    public PAdditionexpression getAdditionexpression()
    {
        return _additionexpression_;
    }

    public void setAdditionexpression(PAdditionexpression node)
    {
        if(_additionexpression_ != null)
        {
            _additionexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additionexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additionexpression_);
    }

    void removeChild(Node child)
    {
        if(_additionexpression_ == child)
        {
            _additionexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additionexpression_ == oldChild)
        {
            setAdditionexpression((PAdditionexpression) newChild);
            return;
        }

    }
}
