/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AAndexpressionExpr extends PExpr
{
    private PAndexpression _andexpression_;

    public AAndexpressionExpr()
    {
    }

    public AAndexpressionExpr(
        PAndexpression _andexpression_)
    {
        setAndexpression(_andexpression_);

    }
    public Object clone()
    {
        return new AAndexpressionExpr(
            (PAndexpression) cloneNode(_andexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndexpressionExpr(this);
    }

    public PAndexpression getAndexpression()
    {
        return _andexpression_;
    }

    public void setAndexpression(PAndexpression node)
    {
        if(_andexpression_ != null)
        {
            _andexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _andexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_andexpression_);
    }

    void removeChild(Node child)
    {
        if(_andexpression_ == child)
        {
            _andexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_andexpression_ == oldChild)
        {
            setAndexpression((PAndexpression) newChild);
            return;
        }

    }
}
