/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ACommaSimple extends PCommaSimple
{
    private TComma _comma_;
    private PSimple _simple_;

    public ACommaSimple()
    {
    }

    public ACommaSimple(
        TComma _comma_,
        PSimple _simple_)
    {
        setComma(_comma_);

        setSimple(_simple_);

    }
    public Object clone()
    {
        return new ACommaSimple(
            (TComma) cloneNode(_comma_),
            (PSimple) cloneNode(_simple_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaSimple(this);
    }

    public TComma getComma()
    {
        return _comma_;
    }

    public void setComma(TComma node)
    {
        if(_comma_ != null)
        {
            _comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comma_ = node;
    }

    public PSimple getSimple()
    {
        return _simple_;
    }

    public void setSimple(PSimple node)
    {
        if(_simple_ != null)
        {
            _simple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _simple_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comma_)
            + toString(_simple_);
    }

    void removeChild(Node child)
    {
        if(_comma_ == child)
        {
            _comma_ = null;
            return;
        }

        if(_simple_ == child)
        {
            _simple_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(_simple_ == oldChild)
        {
            setSimple((PSimple) newChild);
            return;
        }

    }
}
