/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AComparisonexpressionNotexpression extends PNotexpression
{
    private PComparisonexpression _comparisonexpression_;

    public AComparisonexpressionNotexpression()
    {
    }

    public AComparisonexpressionNotexpression(
        PComparisonexpression _comparisonexpression_)
    {
        setComparisonexpression(_comparisonexpression_);

    }
    public Object clone()
    {
        return new AComparisonexpressionNotexpression(
            (PComparisonexpression) cloneNode(_comparisonexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparisonexpressionNotexpression(this);
    }

    public PComparisonexpression getComparisonexpression()
    {
        return _comparisonexpression_;
    }

    public void setComparisonexpression(PComparisonexpression node)
    {
        if(_comparisonexpression_ != null)
        {
            _comparisonexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonexpression_);
    }

    void removeChild(Node child)
    {
        if(_comparisonexpression_ == child)
        {
            _comparisonexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonexpression_ == oldChild)
        {
            setComparisonexpression((PComparisonexpression) newChild);
            return;
        }

    }
}
