/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AConstcharSomething extends PSomething
{
    private TConstchar _constchar_;

    public AConstcharSomething()
    {
    }

    public AConstcharSomething(
        TConstchar _constchar_)
    {
        setConstchar(_constchar_);

    }
    public Object clone()
    {
        return new AConstcharSomething(
            (TConstchar) cloneNode(_constchar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConstcharSomething(this);
    }

    public TConstchar getConstchar()
    {
        return _constchar_;
    }

    public void setConstchar(TConstchar node)
    {
        if(_constchar_ != null)
        {
            _constchar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _constchar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_constchar_);
    }

    void removeChild(Node child)
    {
        if(_constchar_ == child)
        {
            _constchar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_constchar_ == oldChild)
        {
            setConstchar((TConstchar) newChild);
            return;
        }

    }
}
