/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AExitStmt extends PStmt
{
    private TExit _exit_;

    public AExitStmt()
    {
    }

    public AExitStmt(
        TExit _exit_)
    {
        setExit(_exit_);

    }
    public Object clone()
    {
        return new AExitStmt(
            (TExit) cloneNode(_exit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExitStmt(this);
    }

    public TExit getExit()
    {
        return _exit_;
    }

    public void setExit(TExit node)
    {
        if(_exit_ != null)
        {
            _exit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _exit_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_exit_);
    }

    void removeChild(Node child)
    {
        if(_exit_ == child)
        {
            _exit_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_exit_ == oldChild)
        {
            setExit((TExit) newChild);
            return;
        }

    }
}
