/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AFuncDecl extends PFuncDecl
{
    private TDecl _decl_;
    private PHeader _header_;

    public AFuncDecl()
    {
    }

    public AFuncDecl(
        TDecl _decl_,
        PHeader _header_)
    {
        setDecl(_decl_);

        setHeader(_header_);

    }
    public Object clone()
    {
        return new AFuncDecl(
            (TDecl) cloneNode(_decl_),
            (PHeader) cloneNode(_header_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncDecl(this);
    }

    public TDecl getDecl()
    {
        return _decl_;
    }

    public void setDecl(TDecl node)
    {
        if(_decl_ != null)
        {
            _decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _decl_ = node;
    }

    public PHeader getHeader()
    {
        return _header_;
    }

    public void setHeader(PHeader node)
    {
        if(_header_ != null)
        {
            _header_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _header_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_decl_)
            + toString(_header_);
    }

    void removeChild(Node child)
    {
        if(_decl_ == child)
        {
            _decl_ = null;
            return;
        }

        if(_header_ == child)
        {
            _header_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_decl_ == oldChild)
        {
            setDecl((TDecl) newChild);
            return;
        }

        if(_header_ == oldChild)
        {
            setHeader((PHeader) newChild);
            return;
        }

    }
}
