/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AFunctionDefFunction extends PFunction
{
    private PFuncDef _funcDef_;

    public AFunctionDefFunction()
    {
    }

    public AFunctionDefFunction(
        PFuncDef _funcDef_)
    {
        setFuncDef(_funcDef_);

    }
    public Object clone()
    {
        return new AFunctionDefFunction(
            (PFuncDef) cloneNode(_funcDef_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionDefFunction(this);
    }

    public PFuncDef getFuncDef()
    {
        return _funcDef_;
    }

    public void setFuncDef(PFuncDef node)
    {
        if(_funcDef_ != null)
        {
            _funcDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _funcDef_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_funcDef_);
    }

    void removeChild(Node child)
    {
        if(_funcDef_ == child)
        {
            _funcDef_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_funcDef_ == oldChild)
        {
            setFuncDef((PFuncDef) newChild);
            return;
        }

    }
}
