/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AFunctionDeclFunction extends PFunction
{
    private PFuncDecl _funcDecl_;

    public AFunctionDeclFunction()
    {
    }

    public AFunctionDeclFunction(
        PFuncDecl _funcDecl_)
    {
        setFuncDecl(_funcDecl_);

    }
    public Object clone()
    {
        return new AFunctionDeclFunction(
            (PFuncDecl) cloneNode(_funcDecl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionDeclFunction(this);
    }

    public PFuncDecl getFuncDecl()
    {
        return _funcDecl_;
    }

    public void setFuncDecl(PFuncDecl node)
    {
        if(_funcDecl_ != null)
        {
            _funcDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _funcDecl_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_funcDecl_);
    }

    void removeChild(Node child)
    {
        if(_funcDecl_ == child)
        {
            _funcDecl_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_funcDecl_ == oldChild)
        {
            setFuncDecl((PFuncDecl) newChild);
            return;
        }

    }
}
