/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AGreaterComparisonexpression extends PComparisonexpression
{
    private PComparisonexpression _comparisonexpression_;
    private TGreater _greater_;
    private PHashexpression _hashexpression_;

    public AGreaterComparisonexpression()
    {
    }

    public AGreaterComparisonexpression(
        PComparisonexpression _comparisonexpression_,
        TGreater _greater_,
        PHashexpression _hashexpression_)
    {
        setComparisonexpression(_comparisonexpression_);

        setGreater(_greater_);

        setHashexpression(_hashexpression_);

    }
    public Object clone()
    {
        return new AGreaterComparisonexpression(
            (PComparisonexpression) cloneNode(_comparisonexpression_),
            (TGreater) cloneNode(_greater_),
            (PHashexpression) cloneNode(_hashexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterComparisonexpression(this);
    }

    public PComparisonexpression getComparisonexpression()
    {
        return _comparisonexpression_;
    }

    public void setComparisonexpression(PComparisonexpression node)
    {
        if(_comparisonexpression_ != null)
        {
            _comparisonexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonexpression_ = node;
    }

    public TGreater getGreater()
    {
        return _greater_;
    }

    public void setGreater(TGreater node)
    {
        if(_greater_ != null)
        {
            _greater_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _greater_ = node;
    }

    public PHashexpression getHashexpression()
    {
        return _hashexpression_;
    }

    public void setHashexpression(PHashexpression node)
    {
        if(_hashexpression_ != null)
        {
            _hashexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _hashexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonexpression_)
            + toString(_greater_)
            + toString(_hashexpression_);
    }

    void removeChild(Node child)
    {
        if(_comparisonexpression_ == child)
        {
            _comparisonexpression_ = null;
            return;
        }

        if(_greater_ == child)
        {
            _greater_ = null;
            return;
        }

        if(_hashexpression_ == child)
        {
            _hashexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonexpression_ == oldChild)
        {
            setComparisonexpression((PComparisonexpression) newChild);
            return;
        }

        if(_greater_ == oldChild)
        {
            setGreater((TGreater) newChild);
            return;
        }

        if(_hashexpression_ == oldChild)
        {
            setHashexpression((PHashexpression) newChild);
            return;
        }

    }
}
