/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AHashexpressionComparisonexpression extends PComparisonexpression
{
    private PHashexpression _hashexpression_;

    public AHashexpressionComparisonexpression()
    {
    }

    public AHashexpressionComparisonexpression(
        PHashexpression _hashexpression_)
    {
        setHashexpression(_hashexpression_);

    }
    public Object clone()
    {
        return new AHashexpressionComparisonexpression(
            (PHashexpression) cloneNode(_hashexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHashexpressionComparisonexpression(this);
    }

    public PHashexpression getHashexpression()
    {
        return _hashexpression_;
    }

    public void setHashexpression(PHashexpression node)
    {
        if(_hashexpression_ != null)
        {
            _hashexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _hashexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_hashexpression_);
    }

    void removeChild(Node child)
    {
        if(_hashexpression_ == child)
        {
            _hashexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_hashexpression_ == oldChild)
        {
            setHashexpression((PHashexpression) newChild);
            return;
        }

    }
}
