/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AIfStmt extends PStmt
{
    private TIf _if_;
    private PExpr _expr_;
    private TColon _colon_;
    private final LinkedList _stmt_ = new TypedLinkedList(new Stmt_Cast());
    private final LinkedList _elseifStmt_ = new TypedLinkedList(new ElseifStmt_Cast());
    private PElseStmt _elseStmt_;
    private TEnd _end_;

    public AIfStmt()
    {
    }

    public AIfStmt(
        TIf _if_,
        PExpr _expr_,
        TColon _colon_,
        List _stmt_,
        List _elseifStmt_,
        PElseStmt _elseStmt_,
        TEnd _end_)
    {
        setIf(_if_);

        setExpr(_expr_);

        setColon(_colon_);

        {
            this._stmt_.clear();
            this._stmt_.addAll(_stmt_);
        }

        {
            this._elseifStmt_.clear();
            this._elseifStmt_.addAll(_elseifStmt_);
        }

        setElseStmt(_elseStmt_);

        setEnd(_end_);

    }
    public Object clone()
    {
        return new AIfStmt(
            (TIf) cloneNode(_if_),
            (PExpr) cloneNode(_expr_),
            (TColon) cloneNode(_colon_),
            cloneList(_stmt_),
            cloneList(_elseifStmt_),
            (PElseStmt) cloneNode(_elseStmt_),
            (TEnd) cloneNode(_end_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStmt(this);
    }

    public TIf getIf()
    {
        return _if_;
    }

    public void setIf(TIf node)
    {
        if(_if_ != null)
        {
            _if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _if_ = node;
    }

    public PExpr getExpr()
    {
        return _expr_;
    }

    public void setExpr(PExpr node)
    {
        if(_expr_ != null)
        {
            _expr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _expr_ = node;
    }

    public TColon getColon()
    {
        return _colon_;
    }

    public void setColon(TColon node)
    {
        if(_colon_ != null)
        {
            _colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _colon_ = node;
    }

    public LinkedList getStmt()
    {
        return _stmt_;
    }

    public void setStmt(List list)
    {
        _stmt_.clear();
        _stmt_.addAll(list);
    }

    public LinkedList getElseifStmt()
    {
        return _elseifStmt_;
    }

    public void setElseifStmt(List list)
    {
        _elseifStmt_.clear();
        _elseifStmt_.addAll(list);
    }

    public PElseStmt getElseStmt()
    {
        return _elseStmt_;
    }

    public void setElseStmt(PElseStmt node)
    {
        if(_elseStmt_ != null)
        {
            _elseStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _elseStmt_ = node;
    }

    public TEnd getEnd()
    {
        return _end_;
    }

    public void setEnd(TEnd node)
    {
        if(_end_ != null)
        {
            _end_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _end_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_if_)
            + toString(_expr_)
            + toString(_colon_)
            + toString(_stmt_)
            + toString(_elseifStmt_)
            + toString(_elseStmt_)
            + toString(_end_);
    }

    void removeChild(Node child)
    {
        if(_if_ == child)
        {
            _if_ = null;
            return;
        }

        if(_expr_ == child)
        {
            _expr_ = null;
            return;
        }

        if(_colon_ == child)
        {
            _colon_ = null;
            return;
        }

        if(_stmt_.remove(child))
        {
            return;
        }

        if(_elseifStmt_.remove(child))
        {
            return;
        }

        if(_elseStmt_ == child)
        {
            _elseStmt_ = null;
            return;
        }

        if(_end_ == child)
        {
            _end_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(_expr_ == oldChild)
        {
            setExpr((PExpr) newChild);
            return;
        }

        if(_colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        for(ListIterator i = _stmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator i = _elseifStmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_elseStmt_ == oldChild)
        {
            setElseStmt((PElseStmt) newChild);
            return;
        }

        if(_end_ == oldChild)
        {
            setEnd((TEnd) newChild);
            return;
        }

    }

    private class Stmt_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PStmt node = (PStmt) o;

            if((node.parent() != null) &&
                (node.parent() != AIfStmt.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AIfStmt.this))
            {
                node.parent(AIfStmt.this);
            }

            return node;
        }
    }

    private class ElseifStmt_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PElseifStmt node = (PElseifStmt) o;

            if((node.parent() != null) &&
                (node.parent() != AIfStmt.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AIfStmt.this))
            {
                node.parent(AIfStmt.this);
            }

            return node;
        }
    }
}
