/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ALessequalComparisonexpression extends PComparisonexpression
{
    private PComparisonexpression _comparisonexpression_;
    private TLesseq _lesseq_;
    private PHashexpression _hashexpression_;

    public ALessequalComparisonexpression()
    {
    }

    public ALessequalComparisonexpression(
        PComparisonexpression _comparisonexpression_,
        TLesseq _lesseq_,
        PHashexpression _hashexpression_)
    {
        setComparisonexpression(_comparisonexpression_);

        setLesseq(_lesseq_);

        setHashexpression(_hashexpression_);

    }
    public Object clone()
    {
        return new ALessequalComparisonexpression(
            (PComparisonexpression) cloneNode(_comparisonexpression_),
            (TLesseq) cloneNode(_lesseq_),
            (PHashexpression) cloneNode(_hashexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessequalComparisonexpression(this);
    }

    public PComparisonexpression getComparisonexpression()
    {
        return _comparisonexpression_;
    }

    public void setComparisonexpression(PComparisonexpression node)
    {
        if(_comparisonexpression_ != null)
        {
            _comparisonexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonexpression_ = node;
    }

    public TLesseq getLesseq()
    {
        return _lesseq_;
    }

    public void setLesseq(TLesseq node)
    {
        if(_lesseq_ != null)
        {
            _lesseq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _lesseq_ = node;
    }

    public PHashexpression getHashexpression()
    {
        return _hashexpression_;
    }

    public void setHashexpression(PHashexpression node)
    {
        if(_hashexpression_ != null)
        {
            _hashexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _hashexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_comparisonexpression_)
            + toString(_lesseq_)
            + toString(_hashexpression_);
    }

    void removeChild(Node child)
    {
        if(_comparisonexpression_ == child)
        {
            _comparisonexpression_ = null;
            return;
        }

        if(_lesseq_ == child)
        {
            _lesseq_ = null;
            return;
        }

        if(_hashexpression_ == child)
        {
            _hashexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_comparisonexpression_ == oldChild)
        {
            setComparisonexpression((PComparisonexpression) newChild);
            return;
        }

        if(_lesseq_ == oldChild)
        {
            setLesseq((TLesseq) newChild);
            return;
        }

        if(_hashexpression_ == oldChild)
        {
            setHashexpression((PHashexpression) newChild);
            return;
        }

    }
}
