/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ANegativeSignexpression extends PSignexpression
{
    private TMinus _minus_;
    private PSomething _something_;

    public ANegativeSignexpression()
    {
    }

    public ANegativeSignexpression(
        TMinus _minus_,
        PSomething _something_)
    {
        setMinus(_minus_);

        setSomething(_something_);

    }
    public Object clone()
    {
        return new ANegativeSignexpression(
            (TMinus) cloneNode(_minus_),
            (PSomething) cloneNode(_something_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativeSignexpression(this);
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PSomething getSomething()
    {
        return _something_;
    }

    public void setSomething(PSomething node)
    {
        if(_something_ != null)
        {
            _something_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _something_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_minus_)
            + toString(_something_);
    }

    void removeChild(Node child)
    {
        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_something_ == child)
        {
            _something_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_something_ == oldChild)
        {
            setSomething((PSomething) newChild);
            return;
        }

    }
}
