/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ANilSomething extends PSomething
{
    private TNil _nil_;

    public ANilSomething()
    {
    }

    public ANilSomething(
        TNil _nil_)
    {
        setNil(_nil_);

    }
    public Object clone()
    {
        return new ANilSomething(
            (TNil) cloneNode(_nil_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANilSomething(this);
    }

    public TNil getNil()
    {
        return _nil_;
    }

    public void setNil(TNil node)
    {
        if(_nil_ != null)
        {
            _nil_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _nil_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_nil_);
    }

    void removeChild(Node child)
    {
        if(_nil_ == child)
        {
            _nil_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_nil_ == oldChild)
        {
            setNil((TNil) newChild);
            return;
        }

    }
}
