/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ANotNotexpression extends PNotexpression
{
    private TNot _not_;
    private PComparisonexpression _comparisonexpression_;

    public ANotNotexpression()
    {
    }

    public ANotNotexpression(
        TNot _not_,
        PComparisonexpression _comparisonexpression_)
    {
        setNot(_not_);

        setComparisonexpression(_comparisonexpression_);

    }
    public Object clone()
    {
        return new ANotNotexpression(
            (TNot) cloneNode(_not_),
            (PComparisonexpression) cloneNode(_comparisonexpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNotexpression(this);
    }

    public TNot getNot()
    {
        return _not_;
    }

    public void setNot(TNot node)
    {
        if(_not_ != null)
        {
            _not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _not_ = node;
    }

    public PComparisonexpression getComparisonexpression()
    {
        return _comparisonexpression_;
    }

    public void setComparisonexpression(PComparisonexpression node)
    {
        if(_comparisonexpression_ != null)
        {
            _comparisonexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _comparisonexpression_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_not_)
            + toString(_comparisonexpression_);
    }

    void removeChild(Node child)
    {
        if(_not_ == child)
        {
            _not_ = null;
            return;
        }

        if(_comparisonexpression_ == child)
        {
            _comparisonexpression_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(_comparisonexpression_ == oldChild)
        {
            setComparisonexpression((PComparisonexpression) newChild);
            return;
        }

    }
}
