/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class ASubtractionAdditionexpression extends PAdditionexpression
{
    private PAdditionexpression _additionexpression_;
    private TMinus _minus_;
    private PMultiplication _multiplication_;

    public ASubtractionAdditionexpression()
    {
    }

    public ASubtractionAdditionexpression(
        PAdditionexpression _additionexpression_,
        TMinus _minus_,
        PMultiplication _multiplication_)
    {
        setAdditionexpression(_additionexpression_);

        setMinus(_minus_);

        setMultiplication(_multiplication_);

    }
    public Object clone()
    {
        return new ASubtractionAdditionexpression(
            (PAdditionexpression) cloneNode(_additionexpression_),
            (TMinus) cloneNode(_minus_),
            (PMultiplication) cloneNode(_multiplication_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtractionAdditionexpression(this);
    }

    public PAdditionexpression getAdditionexpression()
    {
        return _additionexpression_;
    }

    public void setAdditionexpression(PAdditionexpression node)
    {
        if(_additionexpression_ != null)
        {
            _additionexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _additionexpression_ = node;
    }

    public TMinus getMinus()
    {
        return _minus_;
    }

    public void setMinus(TMinus node)
    {
        if(_minus_ != null)
        {
            _minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _minus_ = node;
    }

    public PMultiplication getMultiplication()
    {
        return _multiplication_;
    }

    public void setMultiplication(PMultiplication node)
    {
        if(_multiplication_ != null)
        {
            _multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _multiplication_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_additionexpression_)
            + toString(_minus_)
            + toString(_multiplication_);
    }

    void removeChild(Node child)
    {
        if(_additionexpression_ == child)
        {
            _additionexpression_ = null;
            return;
        }

        if(_minus_ == child)
        {
            _minus_ = null;
            return;
        }

        if(_multiplication_ == child)
        {
            _multiplication_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_additionexpression_ == oldChild)
        {
            setAdditionexpression((PAdditionexpression) newChild);
            return;
        }

        if(_minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(_multiplication_ == oldChild)
        {
            setMultiplication((PMultiplication) newChild);
            return;
        }

    }
}
