/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import java.util.*;
import tony.analysis.*;

public final class AVariableDefFunction extends PFunction
{
    private PVarDef _varDef_;

    public AVariableDefFunction()
    {
    }

    public AVariableDefFunction(
        PVarDef _varDef_)
    {
        setVarDef(_varDef_);

    }
    public Object clone()
    {
        return new AVariableDefFunction(
            (PVarDef) cloneNode(_varDef_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableDefFunction(this);
    }

    public PVarDef getVarDef()
    {
        return _varDef_;
    }

    public void setVarDef(PVarDef node)
    {
        if(_varDef_ != null)
        {
            _varDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _varDef_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_varDef_);
    }

    void removeChild(Node child)
    {
        if(_varDef_ == child)
        {
            _varDef_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_varDef_ == oldChild)
        {
            setVarDef((PVarDef) newChild);
            return;
        }

    }
}
