/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TDecl extends Token
{
    public TDecl()
    {
        super.setText("decl");
    }

    public TDecl(int line, int pos)
    {
        super.setText("decl");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDecl(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecl(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDecl text.");
    }
}
