/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TElsif extends Token
{
    public TElsif()
    {
        super.setText("elsif");
    }

    public TElsif(int line, int pos)
    {
        super.setText("elsif");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TElsif(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTElsif(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TElsif text.");
    }
}
