/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TGreatereq extends Token
{
    public TGreatereq()
    {
        super.setText(">=");
    }

    public TGreatereq(int line, int pos)
    {
        super.setText(">=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TGreatereq(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGreatereq(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TGreatereq text.");
    }
}
