/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class THash extends Token
{
    public THash()
    {
        super.setText("#");
    }

    public THash(int line, int pos)
    {
        super.setText("#");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THash(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHash(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change THash text.");
    }
}
