/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TMultiplelinescomment extends Token
{
    public TMultiplelinescomment(String text)
    {
        setText(text);
    }

    public TMultiplelinescomment(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMultiplelinescomment(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMultiplelinescomment(this);
    }
}
