/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TMul extends Token
{
    public TMul()
    {
        super.setText("*");
    }

    public TMul(int line, int pos)
    {
        super.setText("*");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TMul(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMul(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TMul text.");
    }
}
