/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TSkip extends Token
{
    public TSkip()
    {
        super.setText("skip");
    }

    public TSkip(int line, int pos)
    {
        super.setText("skip");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TSkip(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSkip(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TSkip text.");
    }
}
