/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.node;

import tony.analysis.*;

public final class TTail extends Token
{
    public TTail()
    {
        super.setText("tail");
    }

    public TTail(int line, int pos)
    {
        super.setText("tail");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TTail(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTail(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TTail text.");
    }
}
