/* This file was generated by SableCC (http://www.sablecc.org/). */

package tony.parser;

import tony.node.*;
import tony.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTDef(TDef node)
    {
        index = 0;
    }

    public void caseTEnd(TEnd node)
    {
        index = 1;
    }

    public void caseTRef(TRef node)
    {
        index = 2;
    }

    public void caseTInt(TInt node)
    {
        index = 3;
    }

    public void caseTBool(TBool node)
    {
        index = 4;
    }

    public void caseTChar(TChar node)
    {
        index = 5;
    }

    public void caseTList(TList node)
    {
        index = 6;
    }

    public void caseTDecl(TDecl node)
    {
        index = 7;
    }

    public void caseTExit(TExit node)
    {
        index = 8;
    }

    public void caseTReturn(TReturn node)
    {
        index = 9;
    }

    public void caseTIf(TIf node)
    {
        index = 10;
    }

    public void caseTElsif(TElsif node)
    {
        index = 11;
    }

    public void caseTElse(TElse node)
    {
        index = 12;
    }

    public void caseTFor(TFor node)
    {
        index = 13;
    }

    public void caseTSkip(TSkip node)
    {
        index = 14;
    }

    public void caseTMod(TMod node)
    {
        index = 15;
    }

    public void caseTTrue(TTrue node)
    {
        index = 16;
    }

    public void caseTFalse(TFalse node)
    {
        index = 17;
    }

    public void caseTNot(TNot node)
    {
        index = 18;
    }

    public void caseTAnd(TAnd node)
    {
        index = 19;
    }

    public void caseTOr(TOr node)
    {
        index = 20;
    }

    public void caseTNew(TNew node)
    {
        index = 21;
    }

    public void caseTNil(TNil node)
    {
        index = 22;
    }

    public void caseTNilquestionmark(TNilquestionmark node)
    {
        index = 23;
    }

    public void caseTHead(THead node)
    {
        index = 24;
    }

    public void caseTTail(TTail node)
    {
        index = 25;
    }

    public void caseTPlus(TPlus node)
    {
        index = 26;
    }

    public void caseTMinus(TMinus node)
    {
        index = 27;
    }

    public void caseTMul(TMul node)
    {
        index = 28;
    }

    public void caseTDiv(TDiv node)
    {
        index = 29;
    }

    public void caseTHash(THash node)
    {
        index = 30;
    }

    public void caseTEq(TEq node)
    {
        index = 31;
    }

    public void caseTNoteq(TNoteq node)
    {
        index = 32;
    }

    public void caseTLess(TLess node)
    {
        index = 33;
    }

    public void caseTGreater(TGreater node)
    {
        index = 34;
    }

    public void caseTLesseq(TLesseq node)
    {
        index = 35;
    }

    public void caseTGreatereq(TGreatereq node)
    {
        index = 36;
    }

    public void caseTLPar(TLPar node)
    {
        index = 37;
    }

    public void caseTRPar(TRPar node)
    {
        index = 38;
    }

    public void caseTLBr(TLBr node)
    {
        index = 39;
    }

    public void caseTRBr(TRBr node)
    {
        index = 40;
    }

    public void caseTComma(TComma node)
    {
        index = 41;
    }

    public void caseTSemicolon(TSemicolon node)
    {
        index = 42;
    }

    public void caseTColon(TColon node)
    {
        index = 43;
    }

    public void caseTAssign(TAssign node)
    {
        index = 44;
    }

    public void caseTId(TId node)
    {
        index = 45;
    }

    public void caseTNumber(TNumber node)
    {
        index = 46;
    }

    public void caseTConstchar(TConstchar node)
    {
        index = 47;
    }

    public void caseTString(TString node)
    {
        index = 48;
    }

    public void caseEOF(EOF node)
    {
        index = 49;
    }
}
